import type { Product, ProductFormat, PreviewId } from "./types";

/**
 * The MÚRÀ catalogue — the approved list, nothing added.
 *
 * Launch set (status "published"): Student Reset (free), Assignment Command Center,
 * Semester System, Grade & TGPA Tracker. Everything else is "upcoming" and switches
 * on by changing its status once the files are ready.
 *
 * REVIEW BEFORE LAUNCH
 * - Prices: every paid `amount` is null until the price catalogue arrives (shown as
 *   "Price coming soon" and not purchasable).
 * - `formats` and bundle contents are proposed defaults and should be confirmed.
 */

const SHEETS: ProductFormat[] = ["Google Sheets", "Excel"];
const ALL_FORMATS: ProductFormat[] = ["PDF", "Google Sheets", "Excel"];
const PRINTABLE: ProductFormat[] = ["PDF"];

const pending = { model: "paid", amount: null } as const;

const sheetSteps = [
  "Complete checkout and receive your download link by email.",
  "Open the Google Sheets version and make a copy, or download the Excel file.",
  "Fill in your details once — everything else updates for you.",
];

const printSteps = [
  "Complete checkout and receive your download link by email.",
  "Download the PDF.",
  "Print it, or write on it with any PDF annotation app.",
];

const mixedSteps = [
  "Complete checkout and receive your download link by email.",
  "Choose your format: printable PDF, Google Sheets or Excel.",
  "Set it up once at the start of term, then return to it every week.",
];

const commonFaqs = [
  {
    q: "How do I receive it?",
    a: "Straight after checkout you'll get an email with a secure download link. No account needed.",
  },
  {
    q: "Is this a subscription?",
    a: "No. You pay once and the files are yours to keep and reuse.",
  },
];

function mini(slug: string, name: string, summary: string, formats: ProductFormat[], previews: PreviewId[] = []): Product {
  return {
    id: `mini-${slug}`,
    slug,
    name,
    kind: "digital",
    type: "mini",
    category: "mini-templates",
    status: "upcoming",
    pricing: pending,
    tagline: summary,
    summary,
    problem: `When you only need a ${name.toLowerCase()}, a full system is more than you need.`,
    audience: ["Students who want one focused tool", "Anyone building their own system piece by piece"],
    includes: [name],
    formats,
    howItWorks: formats.includes("PDF") ? printSteps : sheetSteps,
    previews,
  };
}

export const products: Product[] = [
  /* ------------------------------------------------------------------ */
  /* Free                                                                */
  /* ------------------------------------------------------------------ */
  {
    id: "student-reset",
    slug: "student-reset",
    name: "Mura Student Reset",
    kind: "digital",
    type: "kit",
    category: "academic-systems",
    status: "published",
    featured: true,
    pricing: { model: "free" },
    tagline: "A calm reset for the week ahead — free.",
    summary: "A weekly reset kit to see every deadline, set your priorities and plan your study time. Free to download.",
    problem:
      "Weeks blur together. Deadlines hide in group chats, exams arrive sooner than expected, and it's hard to know what to do first.",
    audience: ["Any student who wants a clear start to each week", "Anyone new to planning who wants a gentle place to begin"],
    includes: [
      "Weekly Reset Template",
      "Assignment Overview",
      "Weekly Study Planner",
      "Weekly Goals",
      "Exam Countdown",
      "Upcoming Deadlines",
      "This Week Priority List",
    ],
    formats: PRINTABLE,
    howItWorks: [
      "Enter your email and we'll send your download link straight away.",
      "Print the pages or use them in any PDF annotation app.",
      "Take twenty minutes each Sunday to reset the week ahead.",
    ],
    previews: ["weekly-reset", "assignment-tracker", "study-planner"],
    faqs: [
      { q: "Is it really free?", a: "Yes. No payment details, no trial. Just your email so we can send the file." },
      {
        q: "Will I be added to a mailing list?",
        a: "We'll only email you your download. If we ever start a newsletter, we'll ask first.",
      },
    ],
    image: {
      alt: "Printed Mura Student Reset pages on a desk in morning light",
      width: 1600,
      height: 2000,
      direction: "Top-down, natural morning light from the left. The printed weekly reset page on warm paper beside a pen and a closed laptop.",
    },
    fileKey: "student-reset/mura-student-reset.pdf",
  },

  /* ------------------------------------------------------------------ */
  /* Academic Systems                                                    */
  /* ------------------------------------------------------------------ */
  {
    id: "semester-starter",
    slug: "semester-starter",
    name: "Mura Semester Starter",
    kind: "digital",
    type: "kit",
    category: "academic-systems",
    status: "upcoming",
    pricing: pending,
    tagline: "Start the semester with everything in its place.",
    summary: "A focused kit for the first weeks of term: courses, timetable, key dates and first goals in one place.",
    problem: "The first weeks of a semester set the tone, but they arrive with new courses, new timetables and a lot to remember.",
    audience: ["Students starting a new semester", "First-year students finding their rhythm"],
    includes: ["Course overview", "Semester timetable", "Key dates tracker", "First-month goals"],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["semester-planner", "calendar"],
    faqs: commonFaqs,
  },
  {
    id: "assignment-command-center",
    slug: "assignment-command-center",
    name: "Mura Assignment Command Center",
    kind: "digital",
    type: "system",
    category: "academic-systems",
    status: "published",
    featured: true,
    pricing: pending,
    tagline: "Every assignment, every deadline, one calm view.",
    summary: "Track every assignment across every course — status, due dates and priorities — so nothing slips through.",
    problem:
      "Assignments arrive from different lecturers, platforms and group chats. Without one place to see them, deadlines are easy to miss.",
    audience: ["Students juggling several courses at once", "Anyone who has ever discovered a deadline too late"],
    includes: ["Assignment tracker", "Course-by-course view", "Due-date overview", "Status and priority tracking"],
    formats: SHEETS,
    howItWorks: sheetSteps,
    previews: ["assignment-tracker", "calendar"],
    faqs: commonFaqs,
    image: {
      alt: "The Mura Assignment Command Center open on a laptop",
      width: 1600,
      height: 2000,
      direction: "Laptop on a walnut desk showing the tracker, soft daylight, a notebook and pen beside it. No people.",
    },
    fileKey: "assignment-command-center/mura-assignment-command-center.zip",
  },
  {
    id: "semester-system",
    slug: "semester-system",
    name: "Mura Semester System",
    kind: "digital",
    type: "system",
    category: "academic-systems",
    status: "published",
    featured: true,
    pricing: pending,
    tagline: "Plan the whole semester once. Follow it every week.",
    summary: "A complete semester system: courses, weekly timetable, assignments, exams and goals, designed to work together.",
    problem:
      "A semester is a long stretch of overlapping courses, deadlines and exams. It's hard to see the whole picture — and easy to fall behind.",
    audience: ["Students who want one system for the whole semester", "Anyone who likes to plan ahead and review weekly"],
    includes: ["Semester overview", "Weekly timetable", "Assignment tracker", "Exam planner", "Semester goals"],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["semester-planner", "assignment-tracker", "calendar", "goal-tracker"],
    faqs: commonFaqs,
    image: {
      alt: "The Mura Semester System printed and on screen",
      width: 1600,
      height: 2000,
      direction: "Printed weekly pages beside a tablet showing the semester overview. Warm paper, linen texture, natural light.",
    },
    fileKey: "semester-system/mura-semester-system.zip",
  },
  {
    id: "exam-prep-system",
    slug: "exam-prep-system",
    name: "Mura Exam Prep System",
    kind: "digital",
    type: "system",
    category: "academic-systems",
    status: "upcoming",
    pricing: pending,
    tagline: "Walk into every exam knowing you've covered it.",
    summary: "Plan revision backwards from each exam date, track topics and past papers, and see your readiness at a glance.",
    problem: "Exam season compresses everything. Without a plan, revision becomes guesswork and the last few days become panic.",
    audience: ["Students preparing for exams", "Anyone who wants a revision plan they can trust"],
    includes: ["Exam countdown", "Revision planner", "Topic checklist", "Past paper tracker"],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["study-planner", "calendar"],
    faqs: commonFaqs,
  },
  {
    id: "grade-tgpa-tracker",
    slug: "grade-tgpa-tracker",
    name: "Mura Grade & TGPA Tracker",
    kind: "digital",
    type: "system",
    category: "academic-systems",
    status: "published",
    featured: true,
    pricing: pending,
    tagline: "Know where your grades stand — before results day.",
    summary: "Record scores, calculate your GPA and TGPA automatically, and see what you need to reach your target.",
    problem: "Most students only learn where they stand when results are published — too late to change anything.",
    audience: ["Students working towards a target grade", "Anyone who wants to understand how their GPA is calculated"],
    includes: ["Course and credit-unit record", "Automatic GPA and TGPA calculation", "Semester-by-semester history", "Target planner"],
    formats: SHEETS,
    howItWorks: sheetSteps,
    previews: ["grade-tracker", "goal-tracker"],
    faqs: [
      ...commonFaqs,
      {
        q: "Does it work with my university's grading scale?",
        a: "The grade points are editable, so you can match the scale your university uses.",
      },
    ],
    image: {
      alt: "The Mura Grade & TGPA Tracker on a laptop screen",
      width: 1600,
      height: 2000,
      direction: "Close crop of the tracker on a laptop with a calculator and pencil. Quiet, even light.",
    },
    fileKey: "grade-tgpa-tracker/mura-grade-tgpa-tracker.zip",
  },

  /* ------------------------------------------------------------------ */
  /* Study Systems                                                       */
  /* ------------------------------------------------------------------ */
  {
    id: "study-planner",
    slug: "study-planner",
    name: "Mura Study Planner",
    kind: "digital",
    type: "system",
    category: "study-systems",
    status: "upcoming",
    pricing: pending,
    tagline: "Give every study session a purpose.",
    summary: "Plan weekly study time around your timetable, set session goals and track the hours you put in.",
    problem: "Studying without a plan means too much time deciding what to study and not enough time studying.",
    audience: ["Students who want consistent study habits", "Anyone balancing study with work or family"],
    includes: ["Weekly study plan", "Session planner", "Study hours log", "Subject balance view"],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["study-planner", "semester-planner"],
    faqs: commonFaqs,
  },
  {
    id: "revision-kit",
    slug: "revision-kit",
    name: "Mura Revision Kit",
    kind: "digital",
    type: "kit",
    category: "study-systems",
    status: "upcoming",
    pricing: pending,
    tagline: "Revise with intent, not just effort.",
    summary: "Printable revision pages for topic lists, active recall, past papers and review cycles.",
    problem: "Re-reading notes feels productive but rarely sticks. Revision works better with structure.",
    audience: ["Students preparing for tests and exams", "Anyone who wants to revise more effectively"],
    includes: ["Topic checklist", "Active recall pages", "Past paper log", "Review schedule"],
    formats: PRINTABLE,
    howItWorks: printSteps,
    previews: ["study-planner"],
    faqs: commonFaqs,
  },
  {
    id: "notes-collection",
    slug: "notes-collection",
    name: "Mura Notes Collection",
    kind: "digital",
    type: "kit",
    category: "study-systems",
    status: "upcoming",
    pricing: pending,
    tagline: "Notes you can find — and understand — later.",
    summary: "A collection of note-taking layouts for lectures, reading and revision, designed to print or annotate.",
    problem: "Notes taken in a rush are hard to use later. A consistent layout makes them easier to review.",
    audience: ["Students who take notes by hand or on a tablet", "Anyone who wants tidier, more useful notes"],
    includes: ["Lecture notes layout", "Reading notes layout", "Cornell-style notes", "Summary pages"],
    formats: PRINTABLE,
    howItWorks: printSteps,
    previews: [],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* University Life                                                     */
  /* ------------------------------------------------------------------ */
  {
    id: "university-starter-kit",
    slug: "university-starter-kit",
    name: "Mura University Starter Kit",
    kind: "digital",
    type: "kit",
    category: "university-life",
    status: "upcoming",
    pricing: pending,
    tagline: "Begin university organised.",
    summary: "Checklists and planners for the move into university life: documents, packing, first weeks and routines.",
    problem: "Starting university means many new responsibilities at once, and it's easy to forget something important.",
    audience: ["Students starting university", "Students moving away from home for the first time"],
    includes: ["Pre-arrival checklist", "Packing checklist", "First-week planner", "Routine builder"],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["packing-checklist", "calendar"],
    faqs: commonFaqs,
  },
  {
    id: "student-budget",
    slug: "student-budget",
    name: "Mura Student Budget",
    kind: "digital",
    type: "system",
    category: "university-life",
    status: "upcoming",
    pricing: pending,
    tagline: "Make your money last the whole semester.",
    summary: "A student budget and expense tracker that shows where your money goes and how much is left each week.",
    problem: "Allowances and part-time income arrive irregularly. Without a plan, the end of the month gets difficult.",
    audience: ["Students managing their own money", "Anyone who wants to spend with less worry"],
    includes: ["Semester budget", "Expense tracker", "Savings tracker", "Weekly spending view"],
    formats: SHEETS,
    howItWorks: sheetSteps,
    previews: ["budget-planner", "expense-tracker"],
    faqs: commonFaqs,
  },
  {
    id: "student-life-planner",
    slug: "student-life-planner",
    name: "Mura Student Life Planner",
    kind: "digital",
    type: "system",
    category: "university-life",
    status: "upcoming",
    pricing: pending,
    tagline: "Room for study, rest and everything in between.",
    summary: "A planner for life around your lectures: routines, habits, goals, events and personal time.",
    problem: "When everything is about deadlines, rest and relationships get squeezed out.",
    audience: ["Students who want balance", "Anyone building healthier routines"],
    includes: ["Monthly planner", "Weekly planner", "Habit tracker", "Goals and reflections"],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["goal-tracker", "calendar"],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* Career & Opportunities                                              */
  /* ------------------------------------------------------------------ */
  {
    id: "internship-tracker",
    slug: "internship-tracker",
    name: "Mura Internship Tracker",
    kind: "digital",
    type: "system",
    category: "career-opportunities",
    status: "upcoming",
    pricing: pending,
    tagline: "Every application, every follow-up, in one place.",
    summary: "Track internship applications, deadlines, contacts and interview stages from first search to offer.",
    problem: "Applying to many internships at once means losing track of deadlines, contacts and follow-ups.",
    audience: ["Students applying for internships", "Anyone preparing for placements or graduate schemes"],
    includes: ["Application tracker", "Deadline overview", "Contacts log", "Interview notes"],
    formats: SHEETS,
    howItWorks: sheetSteps,
    previews: ["assignment-tracker"],
    faqs: commonFaqs,
  },
  {
    id: "scholarship-tracker",
    slug: "scholarship-tracker",
    name: "Mura Scholarship Tracker",
    kind: "digital",
    type: "system",
    category: "career-opportunities",
    status: "upcoming",
    pricing: pending,
    tagline: "Never miss a scholarship deadline again.",
    summary: "Organise scholarship opportunities, requirements, documents and deadlines — and see what to prepare next.",
    problem: "Scholarships have different requirements, documents and deadlines. Keeping them all in your head doesn't work.",
    audience: ["Students applying for funding", "Anyone planning further study"],
    includes: ["Opportunity tracker", "Requirements checklist", "Document tracker", "Deadline calendar"],
    formats: SHEETS,
    howItWorks: sheetSteps,
    previews: ["calendar"],
    faqs: commonFaqs,
  },
  {
    id: "opportunity-tracker",
    slug: "competition-opportunity-tracker",
    name: "Mura Competition & Opportunity Tracker",
    kind: "digital",
    type: "system",
    category: "career-opportunities",
    status: "upcoming",
    pricing: pending,
    tagline: "Competitions, fellowships and programmes — tracked.",
    summary: "Keep competitions, hackathons, fellowships and programmes organised with deadlines and progress.",
    problem: "Great opportunities are announced everywhere and close quickly. Most are missed simply because they're forgotten.",
    audience: ["Students who enter competitions and programmes", "Anyone building experience beyond the classroom"],
    includes: ["Opportunity tracker", "Deadline overview", "Submission checklist", "Outcomes log"],
    formats: SHEETS,
    howItWorks: sheetSteps,
    previews: ["calendar"],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* Career Kits                                                         */
  /* ------------------------------------------------------------------ */
  {
    id: "cv-kit",
    slug: "student-cv-kit",
    name: "Mura Student CV Kit",
    kind: "digital",
    type: "kit",
    category: "career-kits",
    status: "upcoming",
    pricing: pending,
    tagline: "A CV that reflects the work you've done.",
    summary: "Student CV templates and a guide to presenting experience, projects and skills clearly.",
    problem: "Writing a first CV is hard when you're not sure what counts as experience or how to present it.",
    audience: ["Students applying for internships and jobs", "Anyone writing their first CV"],
    includes: ["CV templates", "Writing guide", "Experience worksheet"],
    formats: PRINTABLE,
    howItWorks: printSteps,
    previews: [],
    faqs: commonFaqs,
  },
  {
    id: "portfolio-kit",
    slug: "portfolio-kit",
    name: "Mura Portfolio Kit",
    kind: "digital",
    type: "kit",
    category: "career-kits",
    status: "upcoming",
    pricing: pending,
    tagline: "Show your work with the care it deserves.",
    summary: "Portfolio layouts and a project write-up framework for presenting academic and personal work.",
    problem: "Good work is easy to undersell. A clear structure helps others understand what you did and why it matters.",
    audience: ["Design, architecture, engineering and creative students", "Anyone presenting projects"],
    includes: ["Portfolio layouts", "Project write-up framework", "Case study template"],
    formats: PRINTABLE,
    howItWorks: printSteps,
    previews: [],
    faqs: commonFaqs,
  },
  {
    id: "presentation-kit",
    slug: "presentation-kit",
    name: "Mura Presentation Kit",
    kind: "digital",
    type: "kit",
    category: "career-kits",
    status: "upcoming",
    pricing: pending,
    tagline: "Present with structure and calm.",
    summary: "A presentation planner and slide structure guide for seminars, defences and pitches.",
    problem: "Presentations are often built the night before without a clear structure. Planning makes them easier to deliver.",
    audience: ["Students giving seminars or defences", "Anyone preparing a pitch or talk"],
    includes: ["Presentation planner", "Slide structure guide", "Speaker notes template"],
    formats: PRINTABLE,
    howItWorks: printSteps,
    previews: [],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* Bundles — contents are proposed and should be confirmed             */
  /* ------------------------------------------------------------------ */
  {
    id: "academic-bundle",
    slug: "academic-bundle",
    name: "Mura Academic Bundle",
    kind: "digital",
    type: "bundle",
    category: "bundles",
    status: "upcoming",
    pricing: pending,
    tagline: "The complete academic system, from first lecture to final result.",
    summary: "Every MÚRÀ academic system in one set: semester, assignments, exams and grades.",
    problem: "Separate tools for separate problems create more work. These systems are designed to be used together.",
    audience: ["Students who want their whole academic life organised", "Anyone who wants everything at once"],
    includes: [],
    bundleItems: ["semester-starter", "assignment-command-center", "semester-system", "exam-prep-system", "grade-tgpa-tracker"],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["semester-planner", "assignment-tracker", "grade-tracker"],
    faqs: commonFaqs,
  },
  {
    id: "university-bundle",
    slug: "university-bundle",
    name: "Mura University Bundle",
    kind: "digital",
    type: "bundle",
    category: "bundles",
    status: "upcoming",
    pricing: pending,
    tagline: "Everything for life around your studies.",
    summary: "The University Starter Kit, Student Budget and Student Life Planner together.",
    problem: "University life has many moving parts beyond coursework. This set keeps them organised together.",
    audience: ["Students starting or settling into university"],
    includes: [],
    bundleItems: ["university-starter-kit", "student-budget", "student-life-planner"],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["budget-planner", "goal-tracker"],
    faqs: commonFaqs,
  },
  {
    id: "career-bundle",
    slug: "career-bundle",
    name: "Mura Career Bundle",
    kind: "digital",
    type: "bundle",
    category: "bundles",
    status: "upcoming",
    pricing: pending,
    tagline: "Find opportunities and present yourself well.",
    summary: "Every MÚRÀ opportunity tracker and career kit, from first application to final presentation.",
    problem: "Opportunities and applications need both organisation and presentation. This set covers both.",
    audience: ["Students applying for internships, scholarships and programmes"],
    includes: [],
    bundleItems: ["internship-tracker", "scholarship-tracker", "opportunity-tracker", "cv-kit", "portfolio-kit", "presentation-kit"],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["calendar"],
    faqs: commonFaqs,
  },
  {
    id: "ultimate-student-system",
    slug: "ultimate-student-system",
    name: "MURA Ultimate Student System",
    kind: "digital",
    type: "bundle",
    category: "bundles",
    status: "upcoming",
    featured: true,
    pricing: pending,
    tagline: "Every MÚRÀ system. One complete way to organise student life.",
    summary: "The complete MÚRÀ collection: academic, study, university life and career systems in one set.",
    problem: "Student life touches studies, money, routines and the future. This is everything, designed as one system.",
    audience: ["Students who want the complete set", "Anyone who prefers one purchase to many"],
    includes: [],
    bundleItems: [
      "semester-starter",
      "assignment-command-center",
      "semester-system",
      "exam-prep-system",
      "grade-tgpa-tracker",
      "study-planner",
      "revision-kit",
      "notes-collection",
      "university-starter-kit",
      "student-budget",
      "student-life-planner",
      "internship-tracker",
      "scholarship-tracker",
      "opportunity-tracker",
      "cv-kit",
      "portfolio-kit",
      "presentation-kit",
    ],
    formats: ALL_FORMATS,
    howItWorks: mixedSteps,
    previews: ["semester-planner", "study-planner", "budget-planner", "goal-tracker"],
    faqs: commonFaqs,
  },

  /* ------------------------------------------------------------------ */
  /* Mini Templates                                                      */
  /* ------------------------------------------------------------------ */
  mini("assignment-tracker", "Assignment Tracker", "Track assignments, due dates and status in one simple sheet.", SHEETS, ["assignment-tracker"]),
  mini("exam-countdown", "Exam Countdown", "Count down to every exam and see how much time is left to prepare.", SHEETS, ["calendar"]),
  mini("study-timetable", "Study Timetable", "A weekly study timetable that fits around your lectures.", PRINTABLE, ["study-planner"]),
  mini("weekly-planner", "Weekly Planner", "A clean weekly planner for priorities, tasks and appointments.", PRINTABLE, ["weekly-reset"]),
  mini("monthly-planner", "Monthly Planner", "See the month at a glance: deadlines, events and goals.", PRINTABLE, ["calendar"]),
  mini("grade-tracker", "Grade Tracker", "Record scores by course and watch your average as you go.", SHEETS, ["grade-tracker"]),
  mini("tgpa-calculator", "TGPA Calculator", "Enter your grades and credit units to calculate your TGPA automatically.", SHEETS, ["grade-tracker"]),
  mini("student-budget-template", "Student Budget", "A simple monthly budget for student income and spending.", SHEETS, ["budget-planner"]),
  mini("savings-tracker", "Savings Tracker", "Set a savings goal and watch your progress towards it.", SHEETS, ["goal-tracker"]),
  mini("expense-tracker", "Expense Tracker", "Log daily spending and see where your money goes.", SHEETS, ["expense-tracker"]),
  mini("reading-tracker", "Reading Tracker", "Keep track of set texts, pages read and reading goals.", SHEETS),
  mini("habit-tracker", "Habit Tracker", "Build routines one day at a time with a simple habit grid.", PRINTABLE, ["goal-tracker"]),
  mini("internship-tracker-template", "Internship Tracker", "Track internship applications and deadlines in one sheet.", SHEETS),
  mini("scholarship-tracker-template", "Scholarship Tracker", "Keep scholarship deadlines and requirements in one place.", SHEETS),
  mini("competition-tracker", "Competition Tracker", "Track competitions, submissions and results.", SHEETS),
  mini("project-planner", "Project Planner", "Break a project into tasks, owners and deadlines.", ALL_FORMATS),
  mini("presentation-planner", "Presentation Planner", "Plan the structure, slides and rehearsal of a presentation.", PRINTABLE),
  mini("course-planner", "Course Planner", "Plan the courses you'll take, with credit units and requirements.", SHEETS),
  mini("revision-tracker", "Revision Tracker", "Track topics revised and when to review them again.", SHEETS, ["study-planner"]),
  mini("past-paper-tracker", "Past Paper Tracker", "Log past papers attempted, scores and topics to revisit.", SHEETS),
];
